/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import java.awt.Component;
import java.awt.Container;
import java.awt.Font;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author junio
 */
public class TelaMenuFunc extends javax.swing.JFrame {
     private Map<Component, Font> fontesOriginais = new HashMap<>();
     private double fatorAtual = 1.0; 
    /**
     * Creates new form TelaMenuFunc
     */
    public TelaMenuFunc() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
     private void aplicarZoom(double fator) {
        if (fator == fatorAtual) {
            return; 
        }

        if (fator == 1.0) {
            resetarFontes();
        } else {
            Component[] componentes = this.getContentPane().getComponents();

            for (Component comp : componentes) {
                ajustarComponente(comp, fator);
            }
        }

        fatorAtual = fator;

        this.pack();
        this.revalidate();
        this.repaint();
    }
     

  private void ajustarComponente(Component comp, double fator) {
    
    if (!fontesOriginais.containsKey(comp)) {
        fontesOriginais.put(comp, comp.getFont());
    }

    
    Font original = fontesOriginais.get(comp);
    if (original != null) {
        comp.setFont(original.deriveFont((float) (original.getSize() * fator)));
    }

    
    if (comp instanceof Container) {
        for (Component filho : ((Container) comp).getComponents()) {
            ajustarComponente(filho, fator);
        }
    }
}

    private void resetarFontes() {
        for (Map.Entry<Component, Font> entry : fontesOriginais.entrySet()) {
            entry.getKey().setFont(entry.getValue());
        }

        this.pack();
        this.revalidate();
        this.repaint();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btncadastro = new javax.swing.JButton();
        btnbusca = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnexcluir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        comboMenu = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        menucadastro = new javax.swing.JMenuItem();
        menubusca = new javax.swing.JMenuItem();
        menuedit = new javax.swing.JMenuItem();
        menuexcluir = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menusair = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);

        btncadastro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adicionar.png"))); // NOI18N
        btncadastro.setText("Cadastrar");
        btncadastro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncadastro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastroActionPerformed(evt);
            }
        });

        btnbusca.setBackground(new java.awt.Color(51, 255, 255));
        btnbusca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnbusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisa-de-lupa.png"))); // NOI18N
        btnbusca.setText("Buscar");
        btnbusca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbusca.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnbusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscaActionPerformed(evt);
            }
        });

        btnedit.setBackground(new java.awt.Color(204, 204, 204));
        btnedit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar-arquivo.png"))); // NOI18N
        btnedit.setText("Editar");
        btnedit.setEnabled(false);
        btnedit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnedit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnexcluir.setBackground(new java.awt.Color(0, 255, 51));
        btnexcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        btnexcluir.setText("Excluir");
        btnexcluir.setEnabled(false);
        btnexcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnexcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });

        comboMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100%", "140%", "180%", " " }));

        jButton1.setText("Aplicar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_10024094.png"))); // NOI18N
        jLabel2.setText("  Zoom:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(btncadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(btnexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(670, 670, 670)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboMenu, 0, 89, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(550, 550, 550)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 288, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnexcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(btncadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnbusca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnedit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(278, 278, 278))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 880));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TelaMenu.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 880));

        jMenu3.setText("Opções");

        menucadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        menucadastro.setText("Cadastrar");
        menucadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucadastroActionPerformed(evt);
            }
        });
        jMenu3.add(menucadastro);

        menubusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisa-de-lupa (1).png"))); // NOI18N
        menubusca.setText("Buscar");
        menubusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubuscaActionPerformed(evt);
            }
        });
        jMenu3.add(menubusca);

        menuedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        menuedit.setText("Editar");
        menuedit.setEnabled(false);
        menuedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menueditActionPerformed(evt);
            }
        });
        jMenu3.add(menuedit);

        menuexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bin.png"))); // NOI18N
        menuexcluir.setText("Excluir");
        menuexcluir.setEnabled(false);
        menuexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuexcluirActionPerformed(evt);
            }
        });
        jMenu3.add(menuexcluir);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estoque-pronto.png"))); // NOI18N
        jMenuItem1.setText("Estoque");
        jMenuItem1.setEnabled(false);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/relatorio-de-lucro.png"))); // NOI18N
        jMenuItem2.setText("Relatório");
        jMenuItem2.setEnabled(false);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        menusair.setText("Sair");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        jMenuItem4.setText("Finalizar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menusair.add(jMenuItem4);

        jMenuBar1.add(menusair);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menucadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucadastroActionPerformed
        TelaCadastro tc = new TelaCadastro();
        tc.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_menucadastroActionPerformed

    private void menubuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubuscaActionPerformed
        TelaLista tl = new TelaLista();
        tl.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_menubuscaActionPerformed

    private void menueditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menueditActionPerformed
        TelaSalvar ts = new TelaSalvar();
        ts.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_menueditActionPerformed

    private void menuexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuexcluirActionPerformed
        TelaExcluir te = new TelaExcluir();
        te.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_menuexcluirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaEstoque te = new TelaEstoque();
        te.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaRelatorio tr = new TelaRelatorio();
        tr.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btncadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastroActionPerformed
        TelaCadastro tc = new TelaCadastro();
        tc.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btncadastroActionPerformed

    private void btnbuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscaActionPerformed
        TelaLista tl = new TelaLista();
        tl.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnbuscaActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        TelaSalvar ts = new TelaSalvar();
        ts.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btneditActionPerformed

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
        TelaExcluir te = new TelaExcluir();
        te.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnexcluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String selecionado = (String) comboMenu.getSelectedItem();

        if (selecionado != null && selecionado.endsWith("%")) {
            selecionado = selecionado.replace("%", "");
            try {
                double porcentagem = Double.parseDouble(selecionado);
                double fator = porcentagem / 100.0;
                aplicarZoom(fator);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Zoom inválido.");
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenuFunc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbusca;
    private javax.swing.JButton btncadastro;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JComboBox<String> comboMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menubusca;
    private javax.swing.JMenuItem menucadastro;
    private javax.swing.JMenuItem menuedit;
    private javax.swing.JMenuItem menuexcluir;
    private javax.swing.JMenu menusair;
    // End of variables declaration//GEN-END:variables
}
