/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.AlimentoDAO;
import DAO.EstoqueDAO;
import Modelo.Alimento;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Font;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author junio
 */
public class TelaEstoque extends javax.swing.JFrame {
     private Map<Component, Font> fontesOriginais = new HashMap<>();
     private double fatorAtual = 1.0;
    /**
     * Creates new form te
     */
    public TelaEstoque() {
        initComponents();
    }
    
    private void aplicarZoom(double fator) {
        if (fator == fatorAtual) {
            return;
        }

        if (fator == 1.0) {
            resetarFontes();
        } else {
            Component[] componentes = this.getContentPane().getComponents();

            for (Component comp : componentes) {
                ajustarComponente(comp, fator);
            }
        }

        fatorAtual = fator;

        this.pack();
        this.revalidate();
        this.repaint();
    }
     

  private void ajustarComponente(Component comp, double fator) {
    
    if (!fontesOriginais.containsKey(comp)) {
        fontesOriginais.put(comp, comp.getFont());
    }

    
    Font original = fontesOriginais.get(comp);
    if (original != null) {
        comp.setFont(original.deriveFont((float) (original.getSize() * fator)));
    }

    
    if (comp instanceof Container) {
        for (Component filho : ((Container) comp).getComponents()) {
            ajustarComponente(filho, fator);
        }
    }
}

    private void resetarFontes() {
        for (Map.Entry<Component, Font> entry : fontesOriginais.entrySet()) {
            entry.getKey().setFont(entry.getValue());
        }

        this.pack();
        this.revalidate();
        this.repaint();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();
        btnbusca2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtquanti = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtdata = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        txtusado = new javax.swing.JTextField();
        btnenviar = new javax.swing.JButton();
        btnlimpar = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        btnAcessi = new javax.swing.JButton();
        comboEstoque = new javax.swing.JComboBox<>();
        btnAplicar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        menubusca = new javax.swing.JMenuItem();
        menuedit = new javax.swing.JMenuItem();
        menuexcluir = new javax.swing.JMenuItem();
        menucadastro = new javax.swing.JMenuItem();
        menu = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menusair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setOpaque(false);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Digite o código do produto:");

        txtcod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodKeyTyped(evt);
            }
        });

        btnbusca2.setBackground(new java.awt.Color(0, 51, 204));
        btnbusca2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnbusca2.setForeground(new java.awt.Color(255, 255, 255));
        btnbusca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisa-de-lupa.png"))); // NOI18N
        btnbusca2.setText("Buscar");
        btnbusca2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbusca2btnbuscaActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Nome.png"))); // NOI18N
        jLabel17.setText("Nome:");

        txtnome.setEditable(false);
        txtnome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/caixas (1).png"))); // NOI18N
        jLabel18.setText("Quantidade:");

        txtquanti.setEditable(false);
        txtquanti.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calendario.png"))); // NOI18N
        jLabel19.setText("Data:");

        try {
            txtdata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Movimentação.png"))); // NOI18N
        jLabel20.setText("Movimentação:");

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada", "Saída" }));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/QuantUsada.png"))); // NOI18N
        jLabel21.setText("Quantidade usada:");

        txtusado.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnenviar.setBackground(new java.awt.Color(51, 255, 0));
        btnenviar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnenviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnEnviar.png"))); // NOI18N
        btnenviar.setText("Enviar");
        btnenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenviarActionPerformed(evt);
            }
        });

        btnlimpar.setBackground(new java.awt.Color(204, 204, 204));
        btnlimpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnlimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnLimpar.png"))); // NOI18N
        btnlimpar.setText("Limpar");
        btnlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimparActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_10024094.png"))); // NOI18N
        jLabel22.setText("Zoom:");

        btnAcessi.setBackground(new java.awt.Color(102, 255, 0));
        btnAcessi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnAcessibilidade.png"))); // NOI18N
        btnAcessi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcessibtnAcessiActionPerformed(evt);
            }
        });

        comboEstoque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100%", "140%", "180%" }));

        btnAplicar.setText("Aplicar");
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarbtnAplicarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(btnenviar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnlimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtquanti, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtusado, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnAcessi, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAplicar)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(46, 46, 46)
                                .addComponent(comboEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnbusca2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAplicar)
                        .addGap(18, 18, 18)
                        .addComponent(btnAcessi)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(btnbusca2)
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(txtusado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtquanti, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnenviar)
                    .addComponent(btnlimpar))
                .addGap(37, 37, 37))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 580));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TelaEstoque.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        jMenu3.setText("Opções");

        menubusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisa-de-lupa (1).png"))); // NOI18N
        menubusca.setText("Buscar");
        menubusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubuscaActionPerformed(evt);
            }
        });
        jMenu3.add(menubusca);

        menuedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        menuedit.setText("Editar");
        menuedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menueditActionPerformed(evt);
            }
        });
        jMenu3.add(menuedit);

        menuexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bin.png"))); // NOI18N
        menuexcluir.setText("Excluir");
        menuexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuexcluirActionPerformed(evt);
            }
        });
        jMenu3.add(menuexcluir);

        menucadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        menucadastro.setText("Cadastrar");
        menucadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucadastroActionPerformed(evt);
            }
        });
        jMenu3.add(menucadastro);

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu-bar.png"))); // NOI18N
        menu.setText("Menu");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        jMenu3.add(menu);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/relatorio-de-lucro.png"))); // NOI18N
        jMenuItem2.setText("Relatório");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Sair");

        menusair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        menusair.setText("Finalizar");
        menusair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menusairActionPerformed(evt);
            }
        });
        jMenu4.add(menusair);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menubuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubuscaActionPerformed
        TelaLista tl = new TelaLista();
        tl.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_menubuscaActionPerformed

    private void menueditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menueditActionPerformed
        TelaSalvar tl = new TelaSalvar();
        tl.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_menueditActionPerformed

    private void menuexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuexcluirActionPerformed
        TelaExcluir te = new TelaExcluir();
        te.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_menuexcluirActionPerformed

    private void menucadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucadastroActionPerformed
        TelaCadastro tc = new TelaCadastro();
        tc.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_menucadastroActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        TelaMenu tm = new TelaMenu();
        tm.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_menuActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaRelatorio tr = new TelaRelatorio();
        tr.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menusairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menusairActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_menusairActionPerformed

    private void btnbusca2btnbuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbusca2btnbuscaActionPerformed
      if (txtcod.getText().trim().isEmpty()) {
          JOptionPane.showMessageDialog(null, "Digite o código.");
      }
      else {
      try {
        int id = Integer.parseInt(txtcod.getText()); 
        AlimentoDAO dao = new AlimentoDAO();
        Alimento alimento = dao.busca(id);

        if (alimento != null) {
            txtnome.setText(alimento.getNome());
            txtquanti.setText(String.valueOf(alimento.getQuantidade()));
        } else {
            JOptionPane.showMessageDialog(this, "Alimento não encontrado.");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID inválido.");
    }
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbusca2btnbuscaActionPerformed

    private void btnAcessibtnAcessiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessibtnAcessiActionPerformed
         txtcod.setBackground(Color.black);
         txtcod.setForeground(Color.white);
         txtnome.setBackground(Color.black);
         txtnome.setForeground(Color.white);
         txtquanti.setBackground(Color.black);
         txtquanti.setForeground(Color.white);
         txtdata.setBackground(Color.black);
         txtdata.setForeground(Color.white);
         comboTipo.setBackground(Color.black);
         comboTipo.setForeground(Color.white);
         txtusado.setBackground(Color.black);
         txtusado.setForeground(Color.white);
         
         
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAcessibtnAcessiActionPerformed

    private void btnAplicarbtnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarbtnAplicarActionPerformed
          String selecionado = (String) comboEstoque.getSelectedItem(); 

        if (selecionado != null && selecionado.endsWith("%")) {
            selecionado = selecionado.replace("%", ""); 
            try {
                double porcentagem = Double.parseDouble(selecionado);
                double fator = porcentagem / 100.0;
                aplicarZoom(fator); 
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Zoom inválido.");
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAplicarbtnAplicarActionPerformed

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void btnenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenviarActionPerformed
        if (txtcod.getText().trim().isEmpty() || txtdata.getText().trim().isEmpty() || txtusado.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos.");
        }
        else {
            try {
                int id_alimento = Integer.parseInt(txtcod.getText());

                String dataTexto = txtdata.getText();
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                LocalDate data_ent_sai = LocalDate.parse(dataTexto, formatter);
                String movimentacao = comboTipo.getSelectedItem().toString();
                int quanti_usada = Integer.parseInt(txtusado.getText());

                EstoqueDAO dao = new EstoqueDAO();

                Alimento alimentoExistente = dao.Tela(id_alimento);
                if (alimentoExistente == null) {
                    JOptionPane.showMessageDialog(this, "Alimento não encontrado.");
                    return;
                }

                dao.AdicionarEstoque(id_alimento, movimentacao, data_ent_sai, quanti_usada);
                dao.AtualizarEstoque(id_alimento, quanti_usada, movimentacao);

                Alimento alimentoAtualizado = dao.Tela(id_alimento);
                if (alimentoAtualizado.getQuantidade() <= 20) {
                    JOptionPane.showMessageDialog(this, "O estoque de " + txtnome.getText() + " está baixo");
                }

                JOptionPane.showMessageDialog(this, "Estoque atualizado com sucesso!");
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Código ou quantidade inválidos.");
            } catch (java.time.format.DateTimeParseException e) {
                JOptionPane.showMessageDialog(this, "Data inválida.");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao atualizar estoque: " + e.getMessage());
            }
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_btnenviarActionPerformed

    private void btnlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparActionPerformed
        txtcod.setText("");
        txtnome.setText("");
        txtquanti.setText("");
        txtdata.setText("");
        txtusado.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlimparActionPerformed

    private void txtcodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodKeyTyped
         char c = evt.getKeyChar();
         if (!Character.isDigit(c) || txtcod.getText().length() >= 6) {
        evt.consume();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcessi;
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnbusca2;
    private javax.swing.JButton btnenviar;
    private javax.swing.JButton btnlimpar;
    private javax.swing.JComboBox<String> comboEstoque;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenuItem menu;
    private javax.swing.JMenuItem menubusca;
    private javax.swing.JMenuItem menucadastro;
    private javax.swing.JMenuItem menuedit;
    private javax.swing.JMenuItem menuexcluir;
    private javax.swing.JMenuItem menusair;
    private javax.swing.JTextField txtcod;
    private javax.swing.JFormattedTextField txtdata;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtquanti;
    private javax.swing.JTextField txtusado;
    // End of variables declaration//GEN-END:variables
}
