/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.AlimentoDAO;
import Modelo.Alimento;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Font;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author junio
 */
public class TelaExcluir extends javax.swing.JFrame {
    private Map<Component, Font> fontesOriginais = new HashMap<>();
    private double fatorAtual = 1.0; 
    /**
     * Creates new form TelaExcluir
     */
    public TelaExcluir() {
        initComponents();
    }

     private void aplicarZoom(double fator) {
        if (fator == fatorAtual) {
            return; 
        }

        if (fator == 1.0) {
            resetarFontes();
        } else {
            Component[] componentes = this.getContentPane().getComponents();

            for (Component comp : componentes) {
                ajustarComponente(comp, fator);
            }
        }

        fatorAtual = fator;

        this.pack();
        this.revalidate();
        this.repaint();
    }
     

  private void ajustarComponente(Component comp, double fator) {
    
    if (!fontesOriginais.containsKey(comp)) {
        fontesOriginais.put(comp, comp.getFont());
    }

   
    Font original = fontesOriginais.get(comp);
    if (original != null) {
        comp.setFont(original.deriveFont((float) (original.getSize() * fator)));
    }

    
    if (comp instanceof Container) {
        for (Component filho : ((Container) comp).getComponents()) {
            ajustarComponente(filho, fator);
        }
    }
}

    private void resetarFontes() {
        for (Map.Entry<Component, Font> entry : fontesOriginais.entrySet()) {
            entry.getKey().setFont(entry.getValue());
        }

        this.pack();
        this.revalidate();
        this.repaint();
    }
    
    private void atualizarTabela() {
    AlimentoDAO dao = new AlimentoDAO();
    int id = Integer.parseInt(txtcod.getText());

    Alimento alimento = new Alimento();
    alimento.setId(id);

    List<Alimento> lista = dao.recupera(alimento);
    DefaultTableModel modelo = (DefaultTableModel) TabelaExcluir.getModel();
    modelo.setRowCount(0); 

    for (Alimento a : lista) {
        modelo.addRow(new Object[]{
            a.getId(),
            a.getNome(),
            a.getCategoria(),
            a.getQuantidade(),
            a.getData_val(),
            a.getFornecedor(),
            a.getPreco()
        });
    }
}
    
     


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        btnexcluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaExcluir = new javax.swing.JTable();
        comboExcluir = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAcessi = new javax.swing.JButton();
        btnbusca1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        menubusca = new javax.swing.JMenuItem();
        menuedit = new javax.swing.JMenuItem();
        menucadastro = new javax.swing.JMenuItem();
        menu = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menusair = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Digite o código do insumo:");

        txtcod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodKeyTyped(evt);
            }
        });

        btnbuscar.setBackground(new java.awt.Color(0, 255, 51));
        btnbuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisa-de-lupa.png"))); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btnexcluir.setBackground(new java.awt.Color(255, 255, 0));
        btnexcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnLimpar.png"))); // NOI18N
        btnexcluir.setText("Excluir");
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });

        TabelaExcluir.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        TabelaExcluir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Categoria", "Quantidade", "Data de validade", "fornecedor", "Preço", "Status"
            }
        ));
        TabelaExcluir.setRowHeight(30);
        jScrollPane2.setViewportView(TabelaExcluir);

        comboExcluir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100%", "140%", "180%", " ", " " }));

        jButton1.setText("aplicar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_10024094.png"))); // NOI18N
        jLabel1.setText(" Zoom:");

        btnAcessi.setBackground(new java.awt.Color(51, 255, 0));
        btnAcessi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnAcessibilidade.png"))); // NOI18N
        btnAcessi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcessiActionPerformed(evt);
            }
        });

        btnbusca1.setBackground(new java.awt.Color(204, 204, 204));
        btnbusca1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnbusca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnLimpar.png"))); // NOI18N
        btnbusca1.setText("Limpar");
        btnbusca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbusca1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1113, Short.MAX_VALUE)
                                .addComponent(btnAcessi)))
                        .addGap(15, 15, 15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnbuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnexcluir)
                        .addGap(21, 21, 21)
                        .addComponent(btnbusca1)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jScrollPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnbusca1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnbuscar)
                                .addComponent(btnexcluir))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(btnAcessi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 1470, 360));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TelaExcluir (1).png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1470, 350));

        jMenu3.setText("Opções");

        menubusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisa-de-lupa (1).png"))); // NOI18N
        menubusca.setText("Buscar");
        menubusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubuscaActionPerformed(evt);
            }
        });
        jMenu3.add(menubusca);

        menuedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        menuedit.setText("Editar");
        menuedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menueditActionPerformed(evt);
            }
        });
        jMenu3.add(menuedit);

        menucadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        menucadastro.setText("Cadastrar");
        menucadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucadastroActionPerformed(evt);
            }
        });
        jMenu3.add(menucadastro);

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu-bar.png"))); // NOI18N
        menu.setText("Menu");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        jMenu3.add(menu);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estoque-pronto.png"))); // NOI18N
        jMenuItem2.setText("Estoque");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/relatorio-de-lucro.png"))); // NOI18N
        jMenuItem1.setText("Relatório");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Sair");

        menusair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        menusair.setText("Finalizar");
        menusair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menusairActionPerformed(evt);
            }
        });
        jMenu4.add(menusair);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menubuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubuscaActionPerformed
        TelaLista tl = new TelaLista();
        tl.setVisible(true);
        this.dispose();
                
        // TODO add your handling code here:
    }//GEN-LAST:event_menubuscaActionPerformed

    private void menueditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menueditActionPerformed
        TelaSalvar ts = new TelaSalvar();
        ts.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_menueditActionPerformed

    private void menucadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucadastroActionPerformed
        TelaCadastro tc = new TelaCadastro();
        tc.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_menucadastroActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        TelaMenu tm = new TelaMenu();
        tm.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_menuActionPerformed

    private void menusairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menusairActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_menusairActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaRelatorio tr = new TelaRelatorio();
        tr.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaEstoque te = new TelaEstoque();
        te.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String selecionado = (String) comboExcluir.getSelectedItem(); 

if (selecionado != null && selecionado.endsWith("%")) {
    selecionado = selecionado.replace("%", ""); 
    try {
        double porcentagem = Double.parseDouble(selecionado);
        double fator = porcentagem / 100.0;
        aplicarZoom(fator); // 
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Zoom inválido.");
    }
}

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAcessiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessiActionPerformed
        txtcod.setBackground(Color.black);
        txtcod.setForeground(Color.white);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAcessiActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
    if (txtcod.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Digite o código.");
    }
    else {
    try {
    int id = Integer.parseInt(txtcod.getText());

    Alimento alimento = new Alimento();
    alimento.setId(id);
    AlimentoDAO dao = new AlimentoDAO();
    List<Alimento> Lista = dao.recupera(alimento);  

    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    DefaultTableModel modelo = (DefaultTableModel) TabelaExcluir.getModel();
    modelo.setRowCount(0);  

    for (Alimento resultado : Lista) {
        LocalDate dataValidade = resultado.getData_val();
        LocalDate atual = LocalDate.now();

        String status;
        if (dataValidade.isBefore(atual)) {
            status = "Vencido";
        } else if (!dataValidade.isAfter(atual.plusDays(5))) {
            status = "Próximo do vencimento";
        } else {
            status = "Dentro do prazo";
        }

        modelo.addRow(new Object[]{
            resultado.getNome(),
            resultado.getCategoria(),
            resultado.getQuantidade(),
            dataValidade.format(formatter),
            resultado.getFornecedor(),
            resultado.getPreco(),
            status 
        });
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
}
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
        if (txtcod.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite o código.");
            return;
        }

        int resposta = JOptionPane.showOptionDialog(null,"Deseja excluir este alimento?","Excluir",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null, new Object[] { "Sim", "Não" }, "Não");

        if (resposta == 0) {
            try {
                int id = Integer.parseInt(txtcod.getText());
                AlimentoDAO dao = new AlimentoDAO();

                boolean sucesso = dao.excluir(id);

                if (sucesso) {
                    JOptionPane.showMessageDialog(null, "Alimento excluído com sucesso!");
                    atualizarTabela();
                } else {
                    JOptionPane.showMessageDialog(null, "Nenhum alimento foi excluído.");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "ID inválido.");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao excluir: " + e.getMessage());
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnexcluirActionPerformed

    private void btnbusca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbusca1ActionPerformed
        txtcod.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbusca1ActionPerformed

    private void txtcodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodKeyTyped
         char c = evt.getKeyChar();
         if (!Character.isDigit(c) || txtcod.getText().length() >= 6) {
        evt.consume();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaExcluir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaExcluir;
    private javax.swing.JButton btnAcessi;
    private javax.swing.JButton btnbusca1;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JComboBox<String> comboExcluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem menu;
    private javax.swing.JMenuItem menubusca;
    private javax.swing.JMenuItem menucadastro;
    private javax.swing.JMenuItem menuedit;
    private javax.swing.JMenuItem menusair;
    private javax.swing.JTextField txtcod;
    // End of variables declaration//GEN-END:variables

    
}
